version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
      - ./frontend:/frontend
    depends_on:
      - web
      - frontend
  frontend:
    command: npm run build