version: 1
disable_existing_loggers: false

formatters:
  full_view:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s - %(view)s
    - %(action)s - %(method)s - %(status_code)s - %(request_path)s"
  short:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s "

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: short
    stream: ext://sys.stdout

  file:
    class: logging.handlers.WatchedFileHandler
    level: INFO
    formatter: full_view
    filename: log.txt
    encoding: utf8

root:
  level: NOTSET
  handlers: [console]
  propagate: no

loggers:
  views:
    level: INFO
    handlers: [file]
    propagate: yes
